name: busbuddy
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  form_field_validator: ^1.1.0
  firebase_auth: ^5.3.1
  fluttertoast: ^8.2.8
  dio: ^4.0.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.9.0 # Kept only the latest version to avoid conflicts
  geocoding: ^2.0.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 
flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo1.png
    - assets/images/green.jpg
    - assets/images/lightgreen.jpg
    - assets/images/blue.jpg
    - assets/images/red.jpg
    - assets/images/WatRongKhun.jpg
    - assets/images/WatPhraKaew.jpg
    - assets/images/WatHuayPlaKang.jpg
    - assets/images/WatRongSueaTen.jpg
    - assets/images/WatPhraThatDoiChomThong.jpg
    - assets/images/DoiTungRoyalVilla.jpg
    - assets/images/SinghaPark.jpg
    - assets/images/BaanDam.jpg
    - assets/images/GoldenTrianglePark.jpg
    - assets/images/DoiMaeSalong.jpg
    - assets/images/DoiTung.jpg
    - assets/images/DoiPhuKa.jpg
    - assets/images/DoiPhaTang.jpg
    - assets/images/PhuChiFaForestPark.jpg
    - assets/images/KhunChaeNationalPark.jpg
    - assets/images/KhunKornWaterfall.jpg
    - assets/images/PongPhrabatWaterfall.jpg
    - assets/images/AkhaFarmville.jpg
    - assets/images/MaeSaiBorder.jpg
    - assets/images/ChouiFongTea.jpg
    - assets/images/maekhachanhotspring.jpg


    
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

